### ISSUE TITLE
`logger.js` does not allow multiple args

### ISSUE THREAD

**Issue by anoff** [OpenMined/radar.js#1]
Currently only the first argument passed to `log[type]()` is actually output as a log message.
Need to come up with a smart way how to use spread operator but still allow plain `log('text')` usage

**Comment by kevinahuber** [comment]
@anoff would you want it to output a concatenated string, or a new line for each arg?

**Comment by anoff** [comment]
This just occured to me when I tried to use `log.info(debug1, debug2)` and expected it to work like  `console.log()`. It is outputting them all in one line but separated I think. Would just use the `...spread` operator on the arguments and pass them over to `console.log()`. Just couldn't get it done in a few minutes so I put up an issue :)
